DiagramGenerator.Web/ViewModels/Diagram/DiagramOutputViewModel.cs
using DiagramGenerator.DataAccess.Model.Enum;
using System;
using System.ComponentModel.DataAnnotations;

namespace DiagramGenerator.Web.ViewModels.Diagram
{
    public class DiagramOutputViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        public Guid DiagramId { get; set; }

        public int Lp { get; set; }

        [Required]
        [MinLength(2, ErrorMessage = "Too short Name")]
        public string Name { get; set; }

        public string Description { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Please enter a value bigger than {0}")]
        public int Quantity { get; set; }

        public OutputType Type { get; set; }

        public bool IsSelected { get; set; }

        public string UserEmail { get; set; }
    }
}

DiagramGenerator.Web/Controllers/DiagramInputController.cs
using AutoMapper;
using DiagramGenerator.DataAccess.Model;
using DiagramGenerator.DataAccess.Model.ManyToMany;
using DiagramGenerator.Domain.Services.Interfaces;
using DiagramGenerator.Web.ViewModels;
using DiagramGenerator.Web.ViewModels.Diagram;
using DiagramGenerator.Web.ViewModels.Pages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace DiagramGenerator.Web.Controllers
{
    [Authorize]
    public class DiagramInputController : Controller
    {
        private readonly ILogger<DiagramInputController> logger;
        private readonly IDiagramManager diagramManager;
        private readonly IInputManager inputManager;
        private readonly IProcessManager processManager;
        private readonly IMapper mapper;
        private readonly IMethodManager methodManager;
        private readonly IRequirementManager requirementManager;

        public DiagramInputController(ILogger<DiagramInputController> logger,
             IDiagramManager diagramManager,
             IInputManager inputManager,
             IProcessManager processManager,
             IMethodManager methodManager,
             IRequirementManager requirementManager,
             IMapper mapper)
        {
            this.logger = logger;
            this.diagramManager = diagramManager;
            this.inputManager = inputManager;
            this.processManager = processManager;
            this.methodManager = methodManager;
            this.requirementManager = requirementManager;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index(Guid diagramId)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            var diagram = diagramManager.GetByIdEager(diagramId);
            var inputIds = diagram.Inputs.Select(i => new { i.InputId, i.Quantity } ).ToList();
            var allInputs = mapper.Map<IList<Input>, IList<DiagramInputViewModel>>(inputManager.GetAll(userMail)).ToList();

            foreach (var input in allInputs)
            {
                var existingInput = inputIds.FirstOrDefault(x => x.InputId == input.Id);
                if (existingInput != null)
                {
                    input.IsSelected = true;
                    input.Quantity = existingInput.Quantity;
                }

                input.DiagramId = diagramId;
            }

            var pageViewModel = new DiagramInputPageViewModel()
            {
                DiagramId = diagramId,
                Inputs = allInputs,
            };

            return View(pageViewModel);
        }

        [HttpGet]
        public IActionResult Methods(Guid diagramId)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            var diagram = diagramManager.GetByIdEager(diagramId);

            var methodIds = diagram.Methods.Select(i => new { i.MethodId }).ToList();
            var allMethods = mapper.Map<IList<Method>, IList<DiagramMethodViewModel>>(methodManager.GetAll(userMail)).ToList();

            foreach (var method in allMethods)
            {
                var existingMethod = methodIds.FirstOrDefault(x => x.MethodId == method.Id);
                if (existingMethod != null)
                {
                    method.IsSelected = true;
                }

                method.DiagramId = diagramId;
            }

            var pageViewModel = new DiagramMethodPageViewModel()
            {
                DiagramId = diagramId,
                Methods = allMethods,
            };

            return View(pageViewModel);
        }

        [HttpGet]
        public IActionResult Requirements(Guid diagramId)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            var diagram = diagramManager.GetByIdEager(diagramId);

            var requirementIds = diagram.Requirements.Select(i => new { i.RequirementId }).ToList();
            var allRequirements = mapper.Map<IList<Requirement>, IList<DiagramRequirementViewModel>>(requirementManager.GetAll(userMail)).ToList();

            foreach (var requirement in allRequirements)
            {
                var existingRequirement = requirementIds.FirstOrDefault(x => x.RequirementId == requirement.Id);
                if (existingRequirement != null)
                {
                    requirement.IsSelected = true;
                }

                requirement.DiagramId = diagramId;
            }

            var pageViewModel = new DiagramRequirementPageViewModel()
            {
                DiagramId = diagramId,
                Requirements = allRequirements
            };

            return View(pageViewModel);
        }

        [HttpPost("save-inputs")]
        public IActionResult SaveInputs(DiagramInputPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Inputs edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            model.Inputs = model.Inputs == null ? new List<DiagramInputViewModel>() : model.Inputs;
            var selectedInputs = model.Inputs.Where(x => x.IsSelected == true).ToList();
            //selectedInputs.ForEach(y => y.DiagramId = model.DiagramId);
            diagramManager.UpdateInputs(model.DiagramId, mapper.Map<List<DiagramInputViewModel>, List<DiagramInput>>(selectedInputs));
            return View("Index", model);
        }

        [HttpPost("save-methods")]
        public IActionResult SaveMethods(DiagramMethodPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Methods edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            model.Methods = model.Methods == null ? new List<DiagramMethodViewModel>() : model.Methods;

            var selectedMethods = model.Methods.Where(x => x.IsSelected == true).ToList();
            //selectedInputs.ForEach(y => y.DiagramId = model.DiagramId);
            diagramManager.UpdateMethods(model.DiagramId, mapper.Map<List<DiagramMethodViewModel>, List<DiagramMethod>>(selectedMethods));
            return View("Methods", model);
        }

        [HttpPost("save-requirements")]
        public IActionResult SaveRequirements(DiagramRequirementPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Requirements edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            model.Requirements = model.Requirements == null ? new List<DiagramRequirementViewModel>() : model.Requirements;

            var selectedRequirements = model.Requirements.Where(x => x.IsSelected == true).ToList();
            //selectedInputs.ForEach(y => y.DiagramId = model.DiagramId);
            diagramManager.UpdateRequirements(model.DiagramId, mapper.Map<List<DiagramRequirementViewModel>, List<DiagramRequirement>>(selectedRequirements));
            return View("Requirements", model);
        }


    } 
}

DiagramGenerator.Web/Controllers/DiagramOutputController.cs
using AutoMapper;
using DiagramGenerator.DataAccess.Model;
using DiagramGenerator.DataAccess.Model.ManyToMany;
using DiagramGenerator.Domain.Services.Interfaces;
using DiagramGenerator.Web.ViewModels;
using DiagramGenerator.Web.ViewModels.Diagram;
using DiagramGenerator.Web.ViewModels.Pages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace DiagramGenerator.Web.Controllers
{
    [Authorize]  
    public class DiagramOutputController : Controller
    {
        private readonly ILogger<DiagramOutputController> logger;
        private readonly IDiagramManager diagramManager;
        private readonly IOutputManager outputManager;
        private readonly ICriterionManager criterionManager;
        private readonly IProcessManager processManager;
        private readonly IMapper mapper;


        public DiagramOutputController(ILogger<DiagramOutputController> logger,
             IDiagramManager diagramManager,
             IOutputManager outputManager,
             IProcessManager processManager,
             ICriterionManager criterionManager,
             IMapper mapper)
        {
            this.logger = logger;
            this.diagramManager = diagramManager;
            this.outputManager = outputManager;
            this.processManager = processManager;
            this.criterionManager = criterionManager;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index(Guid diagramId)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            var diagram = diagramManager.GetByIdEager(diagramId);

            var outputIds = diagram.Outputs.Select(i => new { i.OutputId, i.Quantity } ).ToList();
            var allOutputs = mapper.Map<IList<Output>, IList<DiagramOutputViewModel>>(outputManager.GetAll(userMail)).ToList();
           
            foreach (var output in allOutputs)
            {
                var existingOutput = outputIds.FirstOrDefault(x => x.OutputId == output.Id);
                if (existingOutput != null)
                {
                    output.IsSelected = true;
                    output.Quantity = existingOutput.Quantity;
                }
            }

            var pageViewModel = new DiagramOutputPageViewModel()
            {
                DiagramId = diagramId,
                Outputs = allOutputs
            };

            return View(pageViewModel);
        }

        [HttpGet]
        public IActionResult Criteria(Guid diagramId)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            var diagram = diagramManager.GetByIdEager(diagramId);

            var criterionIds = diagram.Criteria.Select(i => new { i.CriterionId }).ToList();
            var allCriteria = mapper.Map<IList<Criterion>, IList<DiagramCriterionViewModel>>(criterionManager.GetAll(userMail)).ToList();

            foreach (var criterion in allCriteria)
            {
                var existingCriterion = criterionIds.FirstOrDefault(x => x.CriterionId == criterion.Id);
                if (existingCriterion != null)
                {
                    criterion.IsSelected = true;
                }
            }

            var pageViewModel = new DiagramCriteriumPageViewModel()
            {
                DiagramId = diagramId,
                Criteria = allCriteria
            };

            return View(pageViewModel);
        }

        [HttpPost("save-outputs")]
        public IActionResult SaveOutputs(DiagramOutputPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Output edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            model.Outputs = model.Outputs == null ? new List<DiagramOutputViewModel>() : model.Outputs;

            var selectedOutputs = model.Outputs.Where(x => x.IsSelected == true).ToList();
            selectedOutputs.ForEach(y => y.DiagramId = model.DiagramId);
            diagramManager.UpdateOutputs(model.DiagramId, mapper.Map<List<DiagramOutputViewModel>, List<DiagramOutput>>(selectedOutputs));
            return View("Index", model);
        }

        [HttpPost("save-criteria")]
        public IActionResult SaveCriteria(DiagramCriteriumPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Criteria edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            model.Criteria = model.Criteria == null ? new List<DiagramCriterionViewModel>() : model.Criteria;

            var selectedCriteria = model.Criteria.Where(x => x.IsSelected == true).ToList();
            selectedCriteria.ForEach(y => y.DiagramId = model.DiagramId);
            diagramManager.UpdateCriteria(model.DiagramId, mapper.Map<List<DiagramCriterionViewModel>, List<DiagramCriterion>>(selectedCriteria));
            return View("Criteria", model);
        }
    } 
}

DiagramGenerator.Web/Views/DiagramOutput/Criteria.cshtml
@model DiagramCriteriumPageViewModel

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "DiagramOutput",  new { diagramId = Model.DiagramId })'" />
</div>

<h4>Criteria</h4>

@using (Html.BeginForm("SaveCriteria", "DiagramOutput", FormMethod.Post))
{
    @Html.HiddenFor(x => x.DiagramId)
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Lp</th>
                <th scope="col">Name</th>
                <th scope="col">Descritpion</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Criteria != null)
            {
                @for (var i = 0; i < Model.Criteria.Count; i++)
                {
                    <tr>
                        @Html.HiddenFor(model => model.Criteria[i].Id)
                        @Html.HiddenFor(model => model.Criteria[i].Name)
                        @Html.HiddenFor(model => model.Criteria[i].Description)
                        @Html.HiddenFor(model => model.Criteria[i].DiagramId)
                        @Html.HiddenFor(model => model.Criteria[i].UserEmail)
                        @Html.HiddenFor(model => model.Criteria[i].Lp)
                        <td>@Html.EditorFor(model => model.Criteria[i].IsSelected)</td>
                        <td>@Html.DisplayFor(model => model.Criteria[i].Lp)</td>
                        <td>@Html.DisplayFor(model => model.Criteria[i].Name)</td>
                        <td>@Html.DisplayFor(model => model.Criteria[i].Description)</td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="submit-button text-center">
        <input type="submit" class="btn btn-info" value="Submit" />
    </div>
    <div class="text-success text-center">@ViewBag.UserMessage</div>
}


<div class="submit-button text-right">
    <input type="button" class="btn btn-info" value="Next" onclick="window.location= '@Url.Action( "Index", "DiagramClientSupplier", new {  diagramId = Model.DiagramId } )'" />
</div>

DiagramGenerator.Web/Views/DiagramOutput/DiagramOutputRow.cshtml
@model DiagramOutputViewModel

<tr>
    <td>@Html.CheckBox("commId", new { value = Model.IsSelected })</td>
    <td>@Model.Id</td>
    <td>@Model.Name</td>
    <td>@Model.Description</td>
    <td>@Model.Type</td>
    <td>@Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @type = "number", @min = "0", @step = "1", @value = "0" } })</td>
</tr>

DiagramGenerator.Web/Views/DiagramOutput/Index.cshtml
@model DiagramOutputPageViewModel

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Requirements", "DiagramInput",  new { diagramId = Model.DiagramId })'" />
</div>

<h4>Outputs</h4>

@using (Html.BeginForm("SaveOutputs", "DiagramOutput", FormMethod.Post))
{
    @Html.HiddenFor(x => x.DiagramId)
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Lp</th>
                <th scope="col">Name</th>
                <th scope="col">Descritpion</th>
                <th scope="col">Type</th>
                <th scope="col">Quantity</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Outputs != null)
            {
                @for (var i = 0; i < Model.Outputs.Count; i++)
                {
                    <tr>
                        @Html.HiddenFor(model => model.Outputs[i].Id)
                        @Html.HiddenFor(model => model.Outputs[i].Name)
                        @Html.HiddenFor(model => model.Outputs[i].Description)
                        @Html.HiddenFor(model => model.Outputs[i].DiagramId)
                        @Html.HiddenFor(model => model.Outputs[i].Type)
                        @Html.HiddenFor(model => model.Outputs[i].UserEmail)
                        @Html.HiddenFor(model => model.Outputs[i].Lp)
                        <td>@Html.EditorFor(model => model.Outputs[i].IsSelected)</td>
                        <td>@Html.DisplayFor(model => model.Outputs[i].Lp)</td>
                        <td>@Html.DisplayFor(model => model.Outputs[i].Name)</td>
                        <td>@Html.DisplayFor(model => model.Outputs[i].Description)</td>
                        <td>@Html.DisplayFor(model => model.Outputs[i].Type)</td>
                        <td>@Html.EditorFor(model => model.Outputs[i].Quantity, new { htmlAttributes = new { @type = "number", @min = "0", @step = "1", @value = "0" } })</td>
                    </tr>
                }
            }
        </tbody>
    </table>

    <div class="submit-button text-center">
        <input type="submit" class="btn btn-info" value="Submit" />
    </div>
    <div class="text-success text-center">@ViewBag.UserMessage</div>
}

<div class="submit-button text-right">
    <input type="button" class="btn btn-info" value="Next" onclick="window.location= '@Url.Action( "Criteria", "DiagramOutput", new {  diagramId = Model.DiagramId } )'" />
</div>