DiagramGenerator.Web/Controllers/DiagramOutputController.cs
using AutoMapper;
using DiagramGenerator.DataAccess.Model;
using DiagramGenerator.DataAccess.Model.ManyToMany;
using DiagramGenerator.Domain.Services.Interfaces;
using DiagramGenerator.Web.ViewModels;
using DiagramGenerator.Web.ViewModels.Diagram;
using DiagramGenerator.Web.ViewModels.Pages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace DiagramGenerator.Web.Controllers
{
    [Authorize]  
    public class DiagramOutputController : Controller
    {
        private readonly ILogger<DiagramOutputController> logger;
        private readonly IDiagramManager diagramManager;
        private readonly IOutputManager outputManager;
        private readonly ICriterionManager criterionManager;
        private readonly IProcessManager processManager;
        private readonly IMapper mapper;


        public DiagramOutputController(ILogger<DiagramOutputController> logger,
             IDiagramManager diagramManager,
             IOutputManager outputManager,
             IProcessManager processManager,
             ICriterionManager criterionManager,
             IMapper mapper)
        {
            this.logger = logger;
            this.diagramManager = diagramManager;
            this.outputManager = outputManager;
            this.processManager = processManager;
            this.criterionManager = criterionManager;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index(Guid diagramId)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            var diagram = diagramManager.GetByIdEager(diagramId);

            var outputIds = diagram.Outputs.Select(i => new { i.OutputId, i.Quantity } ).ToList();
            var allOutputs = mapper.Map<IList<Output>, IList<DiagramOutputViewModel>>(outputManager.GetAll(userMail)).ToList();
           
            foreach (var output in allOutputs)
            {
                var existingOutput = outputIds.FirstOrDefault(x => x.OutputId == output.Id);
                if (existingOutput != null)
                {
                    output.IsSelected = true;
                    output.Quantity = existingOutput.Quantity;
                }
            }

            var pageViewModel = new DiagramOutputPageViewModel()
            {
                DiagramId = diagramId,
                Outputs = allOutputs
            };

            return View(pageViewModel);
        }

        [HttpGet]
        public IActionResult Criteria(Guid diagramId)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            var diagram = diagramManager.GetByIdEager(diagramId);

            var criterionIds = diagram.Criteria.Select(i => new { i.CriterionId }).ToList();
            var allCriteria = mapper.Map<IList<Criterion>, IList<DiagramCriterionViewModel>>(criterionManager.GetAll(userMail)).ToList();

            foreach (var criterion in allCriteria)
            {
                var existingCriterion = criterionIds.FirstOrDefault(x => x.CriterionId == criterion.Id);
                if (existingCriterion != null)
                {
                    criterion.IsSelected = true;
                }
            }

            var pageViewModel = new DiagramCriteriumPageViewModel()
            {
                DiagramId = diagramId,
                Criteria = allCriteria
            };

            return View(pageViewModel);
        }

        [HttpPost("save-outputs")]
        public IActionResult SaveOutputs(DiagramOutputPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Output edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            model.Outputs = model.Outputs == null ? new List<DiagramOutputViewModel>() : model.Outputs;

            var selectedOutputs = model.Outputs.Where(x => x.IsSelected == true).ToList();
            selectedOutputs.ForEach(y => y.DiagramId = model.DiagramId);
            diagramManager.UpdateOutputs(model.DiagramId, mapper.Map<List<DiagramOutputViewModel>, List<DiagramOutput>>(selectedOutputs));
            return View("Index", model);
        }

        [HttpPost("save-criteria")]
        public IActionResult SaveCriteria(DiagramCriteriumPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Criteria edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            model.Criteria = model.Criteria == null ? new List<DiagramCriterionViewModel>() : model.Criteria;

            var selectedCriteria = model.Criteria.Where(x => x.IsSelected == true).ToList();
            selectedCriteria.ForEach(y => y.DiagramId = model.DiagramId);
            diagramManager.UpdateCriteria(model.DiagramId, mapper.Map<List<DiagramCriterionViewModel>, List<DiagramCriterion>>(selectedCriteria));
            return View("Criteria", model);
        }
    } 
}

DiagramGenerator.Web/Controllers/DiagramSummaryController.cs
using AutoMapper;
using DiagramGenerator.DataAccess.Model;
using DiagramGenerator.DataAccess.Model.ManyToMany;
using DiagramGenerator.Domain.Services.Interfaces;
using DiagramGenerator.Web.ViewModels;
using DiagramGenerator.Web.ViewModels.Helpers;
using DiagramGenerator.Web.ViewModels.Pages;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DiagramGenerator.Web.Controllers
{
    [Authorize]
    public class DiagramSummaryController : Controller
    {
        private readonly IDiagramManager diagramManager;
        private readonly IWordExportManager wordExportManager;
        private readonly IMapper mapper;
        private readonly IPdfExportManager pdfExportManager;

        public DiagramSummaryController(
             IDiagramManager diagramManager,
             IWordExportManager wordExportManager,
             IPdfExportManager pdfExportManager,
             IMapper mapper)
        {
            this.diagramManager = diagramManager;
            this.wordExportManager = wordExportManager;
            this.pdfExportManager = pdfExportManager;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index(Guid diagramId)
        {
            var diagram = mapper.Map<Diagram, DiagramSummaryPageViewModel>(diagramManager.GetDiagramIncludeAll(diagramId));
            diagram.Validation = Validation(diagram);
            return View(diagram);
        }

        [HttpPost("generate-diagram")]
        public IActionResult GenerateDiagram(Guid diagramId)
        {
            var diagram = mapper.Map<Diagram, DiagramSummaryPageViewModel>(diagramManager.GetDiagramIncludeAll(diagramId));
            return View("Index", diagramId);
        }

        [HttpGet("generate-word")]
        public IActionResult GenerateWord(Guid diagramId)
        {
            var diagram = diagramManager.GetDiagramIncludeAll(diagramId);

            using (MemoryStream mem = new MemoryStream())
            {
                using (WordprocessingDocument wordDoc = WordprocessingDocument.Create(mem, WordprocessingDocumentType.Document, true))
                {
                    wordExportManager.Export(diagram, wordDoc);
                }

                var fileName = $"{diagram.Name}.docx";

                Response.Headers.Add("Access-Control-Expose-Headers", "Content-Disposition");

                return File(mem.ToArray(), "application/vnd.openxmlformats-officedocument.wordprocessingml.document", fileName);
            }
        }

        [HttpGet("generate-pdf")]
        public IActionResult GeneratePdf(Guid diagramId)
        {
            var diagram = diagramManager.GetDiagramIncludeAll(diagramId);
            var document = pdfExportManager.Export(diagram);
            //Saving the PDF to the MemoryStream
            MemoryStream stream = new MemoryStream();
            document.Save(stream);

            //Set the position as '0'
            stream.Position = 0;

            //Download the PDF document in the browser
            FileStreamResult fileStreamResult = new FileStreamResult(stream, "application/pdf");
            fileStreamResult.FileDownloadName = $"{diagram.Name}.pdf";
            return fileStreamResult;
        }

        private List<ValidationViewModel> Validation(DiagramSummaryPageViewModel model)
        {
            var validation = new List<ValidationViewModel>();

            if (model.Process != null)
            {
                var sum = model.Process.Operations.Sum(x => x.TimeInMinutes);
                var storageOperations = model.Process.Operations.Where(x => x.Type == DataAccess.Model.Enum.OperationType.Storage).Sum(x => x.TimeInMinutes);
                var manufacturingOperations = model.Process.Operations.Where(x => x.Type == DataAccess.Model.Enum.OperationType.Manufacturing).Sum(x => x.TimeInMinutes);
                var controlOperations = model.Process.Operations.Where(x => x.Type == DataAccess.Model.Enum.OperationType.Control).Sum(x => x.TimeInMinutes);
                var transportOperations = model.Process.Operations.Where(x => x.Type == DataAccess.Model.Enum.OperationType.Transport).Sum(x => x.TimeInMinutes);

                validation.Add(new ValidationViewModel() { Text = "Process duration: " + sum });
                validation.Add(new ValidationViewModel() { Text = "Time need for Storage: " + storageOperations });
                validation.Add(new ValidationViewModel() { Text = "Time need for Manufacturing: " + manufacturingOperations });
                validation.Add(new ValidationViewModel() { Text = "Time need for Control: " + controlOperations });
                validation.Add(new ValidationViewModel() { Text = "Time need for Transport: " + transportOperations });
            }
            
            //var humanResources = model.Inputs.Where(y => y.Type == DataAccess.Model.Enum.InputType.HumanResource);
            //var employees = humanResources.Sum(x => x.Quantity);
            //var operationEmployees = model.Process.Operations.Sum(x => x.Employees);
            //if (operationEmployees > employees)
            //{
            //    validation.Add(new ValidationViewModel() { Text = "You have not enough employees: " });
            //    validation.Add(new ValidationViewModel() { Text = "Human Resources: " + employees + " but for operations are needed: " + operationEmployees });
            //} 
            //else if (operationEmployees < employees)
            //{
            //    validation.Add(new ValidationViewModel() { Text = "You have too much employees: " });
            //    validation.Add(new ValidationViewModel() { Text = "Human Resources: " + employees + " but for operations are needed: " + operationEmployees });
            //}

            return validation;
        }
    } 
}

DiagramGenerator.Web/Views/DiagramSummary/Index.cshtml
@model DiagramSummaryPageViewModel

<div class="back-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "DiagramOutput",  new { diagramId = Model.DiagramId })'" />
</div>

<h2 class="text-center">@Model.Name</h2>
<h5 class="text-center">@Model.Description</h5>
@Html.HiddenFor(x => x.DiagramId)

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Purpose</th>
            <th scope="col">Descritpion</th>
            <th colspan="2">
                @if (Model.Process == null)
                {
                    <div class="submit-button">
                        <input type="button" class="btn btn-primary" value="Add Process" onclick="window.location= '@Url.Action("AddProcess", "Process", new { diagramId = Model.DiagramId })'" />
                    </div>
                }
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Process != null)
        {
            <tr>
                <td>@Model.Process.Lp</td>
                <td>@Model.Process.Name</td>
                <td>@Model.Process.Purpose</td>
                <td>@Model.Process.Description</td>
            </tr>
        }
    </tbody>
</table>

<h4 class="text-center">Operations</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
            <th scope="col">Type</th>
            <th scope="col">Number of Employees</th>
            <th scope="col">Duration</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Process?.Operations != null)
        {
            @foreach (var data in Model.Process.Operations)
            {
                <tr>
                    <td>@data.Lp</td>
                    <td>@data.Name</td>
                    <td>@data.Description</td>
                    <td>@data.Type</td>
                    <td>@data.Employees</td>
                    <td>@data.TimeInMinutes</td>
                </tr>
            }
        }
    </tbody>
</table>

<h4 class="text-center">Inputs</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
            <th scope="col">Quantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Inputs)
        {
            <tr>
                <td>@data.Lp</td>
                <td>@data.Name</td>
                <td>@data.Description</td>
                <td>@data.Quantity</td>
            </tr>
        }
    </tbody>
</table>

<h4 class="text-center">Methods</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Methods)
        {
            <tr>
                <td>@data.Lp</td>
                <td>@data.Name</td>
                <td>@data.Description</td>
            </tr>
        }
    </tbody>
</table>

<h4 class="text-center">Requirements</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Requirements)
        {
            <tr>
                <td>@data.Lp</td>
                <td>@data.Name</td>
                <td>@data.Description</td>
            </tr>
        }
    </tbody>
</table>

<h4 class="text-center">Outputs</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
            <th scope="col">Quantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Outputs)
        {
            <tr>
                <td>@data.Lp</td>
                <td>@data.Name</td>
                <td>@data.Description</td>
                <td>@data.Quantity</td>
            </tr>
        }
    </tbody>
</table>

<h4 class="text-center">Criteria</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Criteria)
        {
            <tr>
                <td>@data.Lp</td>
                <td>@data.Name</td>
                <td>@data.Description</td>
            </tr>
        }
    </tbody>
</table>


<h4 class="text-center">Suppliers</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Suppliers)
        {
            <tr>
                <td>@data.Lp</td>
                <td>@data.Name</td>
                <td>@data.Description</td>
            </tr>
        }
    </tbody>
</table>

<h4 class="text-center">Clients</h4>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Lp</th>
            <th scope="col">Name</th>
            <th scope="col">Descritpion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Clients)
        {
            <tr>
                <td>@data.Lp</td>
                <td>@data.Name</td>
                <td>@data.Description</td>
            </tr>
        }
    </tbody>
</table>

<h4 class="text-center">Validation</h4>
@foreach (var data in Model.Validation)
{
    <p>@data.Text</p>
}

@if (Model.Process == null)
{
<tr>
    <div class="submit-button text-center">
        You need to add Process for Diagram
    </div>
</tr>
<tr>  
</tr>
<tr>
</tr>
}
else
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    <div class="submit-button text-center">
                        <input type="button" class="btn btn-info" value="Generate Diagram Word" onclick="window.location= '@Url.Action( "GenerateWord", "DiagramSummary", new {  diagramId = Model.DiagramId } )'" />
                    </div>
                </th>
                <th>
                    <div class="submit-button text-center">
                        <input type="button" class="btn btn-info" value="Generate Diagram Pdf" onclick="window.location= '@Url.Action( "GeneratePdf", "DiagramSummary", new {  diagramId = Model.DiagramId } )'" />
                    </div>
                </th>
            </tr>
        </thead>
    </table>

}

@*<div class="submit-button text-center">
        <input type="button" class="btn btn-info" value="Generate Diagram" onclick="window.location= '@Url.Action( "GenerateWord", "DiagramSummary", new {  diagramId = Model.DiagramId } )'" />
    </div>*@