DiagramGenerator.Web/ViewModels/InputViewModel.cs
using DiagramGenerator.DataAccess.Model.Enum;
using DiagramGenerator.Web.ViewModels.Interfaces;
using System;
using System.ComponentModel.DataAnnotations;

namespace DiagramGenerator.Web.ViewModels
{
    public class InputViewModel : IUserViewModel
    {
        [Required]
        public Guid Id { get; set; }

        public int Lp { get; set; }

        [Required]
        [MinLength(2, ErrorMessage = "Too short Name")]
        public string Name { get; set; }

        public string Description { get; set; }

        public InputType Type { get; set; }

        public string UserEmail { get; set; }
    }
}

DiagramGenerator.Web/Controllers/InputController.cs
using AutoMapper;
using DiagramGenerator.DataAccess.Model;
using DiagramGenerator.DataAccess.Model.Enum;
using DiagramGenerator.Domain.Services.Interfaces;
using DiagramGenerator.Web.ViewModels;
using DiagramGenerator.Web.ViewModels.Pages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace DiagramGenerator.Web.Controllers
{
    [Authorize]
    public class InputController : Controller
    {
        private readonly ILogger<DiagramController> logger;
        private readonly IDiagramManager diagramManager;
        private readonly IInputManager inputManager;
        private readonly IRequirementManager requirementManager;
        private readonly IMethodManager methodManager;
        private readonly IMapper mapper;


        public InputController(ILogger<DiagramController> logger,
             IDiagramManager diagramManager,
             IInputManager inputManager,
             IRequirementManager requirementManager,
             IMethodManager methodManager,
             IMapper mapper)
        {
            this.logger = logger;
            this.diagramManager = diagramManager;
            this.inputManager = inputManager;
            this.requirementManager = requirementManager;
            this.methodManager = methodManager;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {   
            ViewBag.PageTitle = "Inputs";
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;

            var model = new InputPageViewModel()
            {
                Inputs = mapper.Map<IList<Input>, IList<InputViewModel>>(inputManager.GetAll(userMail)),
                Requirements = mapper.Map<IList<Requirement>, IList<RequirementViewModel>>(requirementManager.GetAll(userMail)),
                Methods = mapper.Map<IList<Method>, IList<MethodViewModel>>(methodManager.GetAll(userMail)),
            };

            return View(model);
        }

        //[HttpGet]
        //public ActionResult<IList<Input>> Get(bool includeItems = true)
        //{
        //    string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
        //    return Ok(mapper.Map<IList<Input>, IList<InputViewModel>>(inputManager.GetAll(userMail)));
        //}

        //[HttpGet("{id}")]
        //public ActionResult<Input> Get(Guid id)
        //{
        //    return Ok(mapper.Map<Input, InputViewModel>(inputManager.GetById(id)));
        //}

        [HttpPost("add-input")]
        public IActionResult AddInput(InputViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "New Input created successfully";
                ModelState.Clear();
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            inputManager.Create(mapper.Map<InputViewModel, Input>(model));
            return View(model);
        }

        [HttpGet("add-input")]
        public IActionResult AddInput(InputType type)
        {
            return View(new InputViewModel { Type = type });
        }

        [HttpPost("edit-input")]
        public IActionResult EditInput(InputViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Input edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            inputManager.Update(model.Id, mapper.Map<InputViewModel, Input>(model));
            return View(model);
        }

        [HttpGet("edit-input")]
        public IActionResult EditInput(Guid id)
        {
            var input = mapper.Map<Input, InputViewModel>(inputManager.GetById(id));
            return View(input);
        }

        [HttpGet("remove-input")]
        public IActionResult RemoveInput(Guid id)
        {
            inputManager.Delete(id);
            ViewBag.PageTitle = "Inputs";
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;

            var model = new InputPageViewModel()
            {
                Inputs = mapper.Map<IList<Input>, IList<InputViewModel>>(inputManager.GetAll(userMail)),
                Requirements = mapper.Map<IList<Requirement>, IList<RequirementViewModel>>(requirementManager.GetAll(userMail)),
                Methods = mapper.Map<IList<Method>, IList<MethodViewModel>>(methodManager.GetAll(userMail)),
            };

            return View("Index", model);
        }

        [HttpPost("add-requirement")]
        public IActionResult AddRequirement(RequirementViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "New Requirement created successfully";
                ModelState.Clear();
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            requirementManager.Create(mapper.Map<RequirementViewModel, Requirement>(model));
            return View(model);
        }

        [HttpGet("add-requirement")]
        public IActionResult AddRequirement()
        {
            return View();
        }

        [HttpPost("edit-requirement")]
        public IActionResult EditRequirement(RequirementViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Requirement edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            requirementManager.Update(model.Id, mapper.Map<RequirementViewModel, Requirement>(model));
            return View(model);
        }

        [HttpGet("edit-requirement")]
        public IActionResult EditRequirement(Guid id)
        {
            var requirement = mapper.Map<Requirement, RequirementViewModel>(requirementManager.GetById(id));
            return View(requirement);
        }

        [HttpGet("remove-requirement")]
        public IActionResult RemoveRequirement(Guid id)
        {
            requirementManager.Delete(id);
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;

            var model = new InputPageViewModel()
            {
                Inputs = mapper.Map<IList<Input>, IList<InputViewModel>>(inputManager.GetAll(userMail)),
                Requirements = mapper.Map<IList<Requirement>, IList<RequirementViewModel>>(requirementManager.GetAll(userMail)),
                Methods = mapper.Map<IList<Method>, IList<MethodViewModel>>(methodManager.GetAll(userMail)),
            };

            return View("Index", model);
        }

        [HttpPost("add-method")]
        public IActionResult AddMethod(MethodViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "New Method created successfully";
                ModelState.Clear();
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            methodManager.Create(mapper.Map<MethodViewModel, Method>(model));
            return View(model);
        }

        [HttpGet("add-method")]
        public IActionResult AddMethod()
        {
            return View();
        }

        [HttpPost("edit-method")]
        public IActionResult EditMethod(MethodViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Requirement edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            methodManager.Update(model.Id, mapper.Map<MethodViewModel, Method>(model));
            return View(model);
        }

        [HttpGet("edit-method")]
        public IActionResult EditMethod(Guid id)
        {
            var method = mapper.Map<Method, MethodViewModel>(methodManager.GetById(id));
            return View(method);
        }

        [HttpGet("remove-method")]
        public IActionResult RemoveMethod(Guid id)
        {
            methodManager.Delete(id);
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;

            var model = new InputPageViewModel()
            {
                Inputs = mapper.Map<IList<Input>, IList<InputViewModel>>(inputManager.GetAll(userMail)),
                Requirements = mapper.Map<IList<Requirement>, IList<RequirementViewModel>>(requirementManager.GetAll(userMail)),
                Methods = mapper.Map<IList<Method>, IList<MethodViewModel>>(methodManager.GetAll(userMail)),
            };

            return View("Index", model);
        }
    } 
}

DiagramGenerator.Web/Views/Input/AddInput.cshtml
@model InputViewModel
@{
    ViewBag.PageTitle = "Add " + EnumHelper<DiagramGenerator.DataAccess.Model.Enum.InputType>.GetDisplayValue(Model.Type);
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "Input" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="AddInput" asp-controller="Input">
            <div asp-validation-summary="ModelOnly"></div>
            @Html.HiddenFor(x => x.Type)
            <div class="form-group">
                <label asp-for="Name">Input Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/Input/AddMethod.cshtml
@model MethodViewModel
@{
    ViewBag.PageTitle = "Add Method";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "Input" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="AddMethod" asp-controller="Input">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/Input/AddRequirement.cshtml
@model RequirementViewModel
@{
    ViewBag.PageTitle = "Add Requirement";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "Input" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="AddRequirement" asp-controller="Input">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/Input/EditInput.cshtml
@model InputViewModel
@{
    ViewBag.PageTitle = "Edit " + EnumHelper<DiagramGenerator.DataAccess.Model.Enum.InputType>.GetDisplayValue(Model.Type);
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "Input" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="EditInput" asp-controller="Input">
            <div asp-validation-summary="ModelOnly"></div>
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.Lp)
            @Html.HiddenFor(x => x.Type)
            <div class="form-group">
                <label asp-for="Name">Input Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/Input/EditMethod.cshtml
@model MethodViewModel
@{
    ViewBag.PageTitle = "Edit Method";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "Input" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="EditMethod" asp-controller="Input">
            <div asp-validation-summary="ModelOnly"></div>
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.Lp)
            <div class="form-group">
                <label asp-for="Name">Requirement Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/Input/EditRequirement.cshtml
@model RequirementViewModel
@{
    ViewBag.PageTitle = "Edit Requirement";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "Input" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="EditRequirement" asp-controller="Input">
            <div asp-validation-summary="ModelOnly"></div>
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.Lp)
            <div class="form-group">
                <label asp-for="Name">Requirement Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/Input/Index.cshtml
@model InputPageViewModel
@*<h2>@ViewBag.PageTitle</h2>*@

<h4>Equipment</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary"
                           value="Add"
                           onclick="window.location= '@Url.Action( "AddInput", "Input", new { type =  DiagramGenerator.DataAccess.Model.Enum.InputType.Equipment})'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Inputs.Where(x => x.Type == DiagramGenerator.DataAccess.Model.Enum.InputType.Equipment))
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditInput", "Input", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveInput", "Input", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>


<h4>Materials</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary" value="Add" onclick="window.location= '@Url.Action( "AddInput", "Input", new { type =  DiagramGenerator.DataAccess.Model.Enum.InputType.Material})'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Inputs.Where(x => x.Type == DiagramGenerator.DataAccess.Model.Enum.InputType.Material))
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditInput", "Input", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveInput", "Input", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>


<h4>Human Resources</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary" value="Add" onclick="window.location= '@Url.Action( "AddInput", "Input", new { type =  DiagramGenerator.DataAccess.Model.Enum.InputType.HumanResource})'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Inputs.Where(x => x.Type == DiagramGenerator.DataAccess.Model.Enum.InputType.HumanResource))
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditInput", "Input", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveInput", "Input", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>


<h4>Documents</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary" value="Add" onclick="window.location= '@Url.Action( "AddInput", "Input", new { type =  DiagramGenerator.DataAccess.Model.Enum.InputType.Document})'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Inputs.Where(x => x.Type == DiagramGenerator.DataAccess.Model.Enum.InputType.Document))
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditInput", "Input", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveInput", "Input", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>
<br />

<h4>Other</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary" value="Add" onclick="window.location= '@Url.Action( "AddInput", "Input", new { type =  DiagramGenerator.DataAccess.Model.Enum.InputType.Other})'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Inputs.Where(x => x.Type == DiagramGenerator.DataAccess.Model.Enum.InputType.Other))
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditInput", "Input", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveInput", "Input", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>
<br />


<br />
<h4>Requirements</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary" value="Add" onclick="window.location= '@Url.Action( "AddRequirement", "Input")'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Requirements)
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditRequirement", "Input", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveRequirement", "Input", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>
<br />

<br />
<h4>Methods</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary" value="Add" onclick="window.location= '@Url.Action( "AddMethod", "Input")'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Methods)
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditMethod", "Input", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveMethod", "Input", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>