DiagramGenerator.Web/Controllers/ClientSupplierController.cs
using AutoMapper;
using DiagramGenerator.DataAccess.Model;
using DiagramGenerator.DataAccess.Model.Enum;
using DiagramGenerator.Domain.Services.Interfaces;
using DiagramGenerator.Web.ViewModels;
using DiagramGenerator.Web.ViewModels.Pages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace DiagramGenerator.Web.Controllers
{
    [Authorize]
    public class ClientSupplierController : Controller
    {
        private readonly IDiagramManager diagramManager;
        private readonly IClientManager clientManager;
        private readonly ISupplierManager supplierManager;
        private readonly IMapper mapper;


        public ClientSupplierController(
             IDiagramManager diagramManager,
             IClientManager clientManager,
             ISupplierManager supplierManager,
             IMapper mapper)
        {
            this.diagramManager = diagramManager;
            this.clientManager = clientManager;
            this.supplierManager = supplierManager;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.PageTitle = "Clients and Suppliers";
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;

            var model = new ClientSupplierPageViewModel()
            {
                Clients = mapper.Map<IList<Client>, IList<ClientViewModel>>(clientManager.GetAll(userMail)),
                Suppliers = mapper.Map<IList<Supplier>, IList<SupplierViewModel>>(supplierManager.GetAll(userMail)),
            };

            return View(model);
        }

        //[HttpGet("clients/{id}")]
        //public ActionResult<Input> Get(Guid id)
        //{
        //    return Ok(mapper.Map<Client, ClientViewModel>(clientManager.GetById(id)));
        //}

        [HttpPost("add-client")]
        public IActionResult AddClient(ClientViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "New Client created successfully";
                ModelState.Clear();
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            clientManager.Create(mapper.Map<ClientViewModel, Client>(model));
            return View(model);
        }

        [HttpGet("add-client")]
        public IActionResult AddClient()
        {
            return View(new ClientViewModel());
        }

        [HttpPost("edit-client")]
        public IActionResult EditClient(ClientViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Client edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            clientManager.Update(model.Id, mapper.Map<ClientViewModel, Client>(model));
            return View(model);
        }

        [HttpGet("edit-client")]
        public IActionResult EditClient(Guid id)
        {
            var client = mapper.Map<Client, ClientViewModel>(clientManager.GetById(id));
            return View(client);
        }

        [HttpGet("remove-client")]
        public IActionResult RemoveClient(Guid id)
        {
            clientManager.Delete(id);
            ViewBag.PageTitle = "Clients";
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;

            var model = new ClientSupplierPageViewModel()
            {
                Clients = mapper.Map<IList<Client>, IList<ClientViewModel>>(clientManager.GetAll(userMail)),
                Suppliers = mapper.Map<IList<Supplier>, IList<SupplierViewModel>>(supplierManager.GetAll(userMail)),
            };

            return View("Index", model);
        }

        [HttpPost("add-supplier")]
        public IActionResult AddSupplier(SupplierViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "New Supplier created successfully";
                ModelState.Clear();
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            supplierManager.Create(mapper.Map<SupplierViewModel, Supplier>(model));
            return View(model);
        }

        [HttpGet("add-supplier")]
        public IActionResult AddSupplier()
        {
            return View();
        }

        [HttpPost("edit-supplier")]
        public IActionResult EditSupplier(SupplierViewModel model)
        {
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;
            model.UserEmail = userMail;
            if (ModelState.IsValid)
            {
                ViewBag.UserMessage = "Supplier edited successfully";
            }
            else
            {
                return BadRequest("Invalid Model");
            }

            supplierManager.Update(model.Id, mapper.Map<SupplierViewModel, Supplier>(model));
            return View(model);
        }

        [HttpGet("edit-supplier")]
        public IActionResult EditSupplier(Guid id)
        {
            var supplier = mapper.Map<Supplier, SupplierViewModel>(supplierManager.GetById(id));
            return View(supplier);
        }

        [HttpGet("remove-supplier")]
        public IActionResult RemoveSupplier(Guid id)
        {
            supplierManager.Delete(id);
            string userMail = User.FindFirst(ClaimTypes.Name)?.Value;

            var model = new ClientSupplierPageViewModel()
            {
                Clients = mapper.Map<IList<Client>, IList<ClientViewModel>>(clientManager.GetAll(userMail)),
                Suppliers = mapper.Map<IList<Supplier>, IList<SupplierViewModel>>(supplierManager.GetAll(userMail)),
            };

            return View("Index", model);
        }
    } 
}

DiagramGenerator.Web/Views/ClientSupplier/AddClient.cshtml
@model ClientViewModel
@{
    ViewBag.PageTitle = "Add Client";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "ClientSupplier" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="AddClient" asp-controller="ClientSupplier">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/ClientSupplier/AddSupplier.cshtml
@model SupplierViewModel
@{
    ViewBag.PageTitle = "Add Supplier";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "ClientSupplier" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="AddSupplier" asp-controller="ClientSupplier">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/ClientSupplier/EditClient.cshtml
@model ClientViewModel
@{
    ViewBag.PageTitle = "Edit Client";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "ClientSupplier" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="EditClient" asp-controller="ClientSupplier">
            <div asp-validation-summary="ModelOnly"></div>
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.Lp)
            <div class="form-group">
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/ClientSupplier/EditSupplier.cshtml
@model SupplierViewModel
@{
    ViewBag.PageTitle = "Edit Supplier";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
}

<div class="submit-button">
    <input type="button" class="btn btn-info" value="Back" onclick="window.location= '@Url.Action( "Index", "ClientSupplier" )'" />
</div>

<div class="col-md-6 offset-md-3">
    <div class="card card-body bg-light">
        <form method="post" class="theForm" asp-action="EditSupplier" asp-controller="ClientSupplier">
            <div asp-validation-summary="ModelOnly"></div>
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.Lp)
            <div class="form-group">
                <label asp-for="Name">Name:</label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-warning"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <input type="text" asp-for="Description" class="form-control">
                <span asp-validation-for="Description" class="text-warning"></span>
            </div>
            <div class="form-group">
                <div class="submit-button text-center">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
                <div class="text-success text-center">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DiagramGenerator.Web/Views/ClientSupplier/Index.cshtml
@model ClientSupplierPageViewModel
@*<h2>@ViewBag.PageTitle</h2>*@

<h4>Clients</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary"
                           value="Add"
                           onclick="window.location= '@Url.Action( "AddClient", "ClientSupplier")'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Clients)
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditClient", "ClientSupplier", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveClient", "ClientSupplier", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>


<h4>Suppliers</h4>
<table class="table table-hover">
    <thead>
        <tr class="d-flex">
            <th scope="col" class="col-3">Lp</th>
            <th scope="col" class="col-3">Name</th>
            <th scope="col" class="col-4">Descritpion</th>
            <th scope="col" colspan="2" class="col-2">
                <div class="submit-button">
                    <input type="button" class="btn btn-primary" value="Add" onclick="window.location= '@Url.Action( "AddSupplier", "ClientSupplier")'" />
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model.Suppliers)
        {
            <tr class="d-flex">
                <td class="col-3">@data.Lp</td>
                <td class="col-3">@data.Name</td>
                <td class="col-4">@data.Description</td>
                <td class="col-1"><input type="button" class="btn btn-info" value="Edit" onclick="window.location= '@Url.Action( "EditSupplier", "ClientSupplier", new { id = data.Id })'" /></td>
                <td class="col-1"><input type="button" class="btn btn-danger" value="Remove" onclick="window.location= '@Url.Action( "RemoveSupplier", "ClientSupplier", new { id = data.Id })'" /></td>
            </tr>
        }
    </tbody>
</table>